package com.ohgiraffers.MedicalResourceManagementSystem.aggregate;

public enum HospitalBed {
    SECOND_FLOOR_HOSPITAL_BED,
    THIRD_FLOOR_HOSPITAL_BED,
    FIFTH_FLOOR_HOSPITAL_BED,
    SIXTH_FLOOR_HOSPITAL_BED,
    SEVENTH_FLOOR_HOSPITAL_BED,
    EIGHTH_FLOOR_HOSPITAL_BED,
    NINTH_FLOOR_HOSPITAL_BED,
    TENTH_FLOOR_HOSPITAL_BED,
    ELEVENTH_FLOOR_HOSPITAL_BED
}
